// Class profiles and game data
const classProfiles = [
  {
    id: "bm_hunter",
    name: "Hunter (Beast Mastery)",
    tags: ["ranged", "pve_dps", "solo", "demand", "high_apm"],
    profile: {
      raid_dps: 10,
      easy_invites: 9,
      pvp_push: 7,
      flexibility: 4,
      ranged: 10,
      melee: 1,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 3,
      mid: 7,
      high: 9,
      arena_low: 3,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 8,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 5,
      solo_mid: 8,
      solo_high: 10,
      demand_low: 6,
      demand_mid: 9,
      demand_high: 10,
      pet_master: 10,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 2,
      arcane_control: 2,
      shadow_support: 0,
      meta: 9,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Top-tier sustained raid DPS through all major TBC phases",
      "High solo efficiency and safe farming with pet toolkit",
      "Consistent invite value in 25-man physical groups"
    ],
    tradeoffs: [
      "Ceiling gameplay includes timing-sensitive shot weaving",
      "Can feel repetitive if you dislike pet management"
    ],
    nextSteps: "Start as BM with 4pc Beast Lord path from dungeons, then optimize shot rhythm and pet uptime."
  },
  {
    id: "destro_warlock",
    name: "Warlock (Destruction)",
    tags: ["ranged", "pve_dps", "demand"],
    profile: {
      raid_dps: 10,
      easy_invites: 9,
      pvp_push: 6,
      flexibility: 5,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 6,
      mid: 8,
      high: 6,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 6,
      slot_low: 8,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 4,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 9,
      pet_master: 1,
      dark_caster: 10,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 3,
      shadow_support: 4,
      meta: 9,
      balance: 8,
      fun: 6
    },
    strengths: [
      "Reliable raid throughput and strong scaling",
      "Excellent raid utility (summons, stones, curses)",
      "Very stable spot in caster-centric comps"
    ],
    tradeoffs: [
      "Core rotation can feel simple over long sessions",
      "PvP options exist but are comp and spec dependent"
    ],
    nextSteps: "Gear through spell hit/spell power benchmarks, then refine curse and pet utility discipline."
  },
  {
    id: "fire_mage",
    name: "Mage (Fire)",
    tags: ["ranged", "pve_dps", "control"],
    profile: {
      raid_dps: 9,
      easy_invites: 7,
      pvp_push: 7,
      flexibility: 4,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 5,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 5,
      slot_mid: 7,
      slot_high: 8,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 8,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 4,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 4,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 10,
      shadow_support: 0,
      meta: 8,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Strong ranged DPS with high burst windows",
      "Great utility for dungeons and PvP control",
      "Good pick if you enjoy active casting cadence"
    ],
    tradeoffs: [
      "Raid slots can be tighter than lock/hunter in many comps",
      "Performance heavily depends on group buffs and kill times"
    ],
    nextSteps: "Prioritize hit cap and spell power upgrades, then optimize combust windows and utility usage."
  },
  {
    id: "enhance_shaman",
    name: "Shaman (Enhancement)",
    tags: ["melee", "hybrid", "demand", "utility"],
    profile: {
      raid_dps: 7,
      easy_invites: 10,
      pvp_push: 7,
      flexibility: 9,
      ranged: 1,
      melee: 9,
      tank: 0,
      healer: 3,
      hybrid: 10,
      low: 4,
      mid: 8,
      high: 8,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 9,
      slot_mid: 10,
      slot_high: 9,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 7,
      solo_low: 5,
      solo_mid: 8,
      solo_high: 8,
      demand_low: 8,
      demand_mid: 10,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 1,
      totem_fighter: 10,
      shapeshifter: 0,
      weapon_master: 6,
      arcane_control: 0,
      shadow_support: 2,
      meta: 9,
      balance: 10,
      fun: 9
    },
    strengths: [
      "Extremely high raid demand in TBC due to group totem value",
      "Strong hybrid flexibility across PvE and PvP",
      "Engaging support-plus-damage gameplay"
    ],
    tradeoffs: [
      "Totem management can feel busy",
      "Dual-weapon gearing can be awkward in some loot environments"
    ],
    nextSteps: "Secure hit and weapon speed consistency early, then master totem timing per encounter."
  },
  {
    id: "resto_shaman",
    name: "Shaman (Restoration)",
    tags: ["healer", "demand", "utility"],
    profile: {
      raid_dps: 0,
      easy_invites: 10,
      pvp_push: 8,
      flexibility: 9,
      ranged: 2,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 9,
      low: 6,
      mid: 8,
      high: 5,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 10,
      slot_mid: 10,
      slot_high: 9,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 4,
      demand_low: 9,
      demand_mid: 10,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 9,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 0,
      shadow_support: 3,
      meta: 10,
      balance: 9,
      fun: 8
    },
    strengths: [
      "One of the safest invite options in TBC raids",
      "Chain heal plus totems provide huge raid utility",
      "Competitive healer in arena formats"
    ],
    tradeoffs: [
      "Solo speed is weaker than DPS-focused specs",
      "High utility responsibility in optimized groups"
    ],
    nextSteps: "Build healing throughput basics first, then layer in totem swaps and utility discipline."
  },
  {
    id: "feral_druid",
    name: "Druid (Feral Bear/Cat Hybrid)",
    tags: ["melee", "tank", "hybrid", "solo"],
    profile: {
      raid_dps: 6,
      easy_invites: 7,
      pvp_push: 7,
      flexibility: 10,
      ranged: 0,
      melee: 8,
      tank: 8,
      healer: 2,
      hybrid: 10,
      low: 4,
      mid: 8,
      high: 8,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 4,
      solo_mid: 9,
      solo_high: 10,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 10,
      weapon_master: 6,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 10,
      fun: 10
    },
    strengths: [
      "Top-tier flexibility between tanking and DPS assignments",
      "Excellent open-world sustain and movement",
      "Strong value in raids that need adaptable offtanking"
    ],
    tradeoffs: [
      "Pure cat DPS slots are less common than hybrid feral roles",
      "Performance quality depends on encounter role swapping"
    ],
    nextSteps: "Prepare both bear and cat sets early, and communicate your role flexibility with raid leads."
  },
  {
    id: "prot_paladin",
    name: "Paladin (Protection)",
    tags: ["tank", "utility", "demand"],
    profile: {
      raid_dps: 1,
      easy_invites: 8,
      pvp_push: 4,
      flexibility: 8,
      ranged: 0,
      melee: 1,
      tank: 10,
      healer: 1,
      hybrid: 8,
      low: 7,
      mid: 8,
      high: 4,
      arena_low: 3,
      arena_mid: 4,
      arena_high: 5,
      slot_low: 6,
      slot_mid: 8,
      slot_high: 7,
      gear_low: 5,
      gear_mid: 6,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 9,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 10,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 3,
      arcane_control: 0,
      shadow_support: 0,
      meta: 8,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Premier AoE tanking utility in TBC dungeons and raids",
      "Strong support identity with blessings and utility",
      "Can offer stable raid value when threat/gearing is managed"
    ],
    tradeoffs: [
      "Single-target tank optimization can be gear and setup sensitive",
      "Full-time raid tank slots are naturally limited"
    ],
    nextSteps: "Build separate threat and mitigation sets, then align group composition for reliable threat support."
  },
  {
    id: "holy_paladin",
    name: "Paladin (Holy)",
    tags: ["healer", "utility", "demand"],
    profile: {
      raid_dps: 0,
      easy_invites: 8,
      pvp_push: 7,
      flexibility: 6,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 6,
      low: 8,
      mid: 8,
      high: 4,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 7,
      slot_mid: 8,
      slot_high: 7,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 2,
      solo_mid: 4,
      solo_high: 3,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 10,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Reliable single-target healing and excellent mana longevity",
      "Desired utility package in raid environments",
      "Works well for players who like stability and clean execution"
    ],
    tradeoffs: [
      "Lower solo speed than DPS classes",
      "Playstyle can feel repetitive if you prefer high APM"
    ],
    nextSteps: "Prioritize throughput and mana stats early, then refine cooldown and utility timing in raids."
  },
  {
    id: "arms_fury_warrior",
    name: "Warrior (Arms/Fury DPS)",
    tags: ["melee", "high_apm", "scaling"],
    profile: {
      raid_dps: 8,
      easy_invites: 4,
      pvp_push: 8,
      flexibility: 5,
      ranged: 0,
      melee: 10,
      tank: 2,
      healer: 0,
      hybrid: 3,
      low: 2,
      mid: 6,
      high: 10,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 3,
      slot_mid: 5,
      slot_high: 8,
      gear_low: 3,
      gear_mid: 6,
      gear_high: 10,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 5,
      demand_low: 2,
      demand_mid: 4,
      demand_high: 6,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 10,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 6,
      fun: 8
    },
    strengths: [
      "Very rewarding if you enjoy high-precision melee execution",
      "Strong PvP identity and weapon-centric gameplay",
      "Scales hard with proper gear and raid support"
    ],
    tradeoffs: [
      "Raid DPS slots are often competitive in TBC",
      "Feels weak early if undergeared or under-supported"
    ],
    nextSteps: "Target hit/crit benchmarks fast and secure stable raid buffs before judging final performance."
  },
  {
    id: "priest_shadow",
    name: "Priest (Shadow)",
    tags: ["ranged", "utility", "support_dps"],
    profile: {
      raid_dps: 5,
      easy_invites: 7,
      pvp_push: 8,
      flexibility: 7,
      ranged: 9,
      melee: 0,
      tank: 0,
      healer: 2,
      hybrid: 7,
      low: 5,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 7,
      gear_mid: 7,
      gear_high: 6,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 7,
      demand_low: 5,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 7,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 4,
      shadow_support: 10,
      meta: 8,
      balance: 9,
      fun: 8
    },
    strengths: [
      "Great utility-DPS niche in caster groups",
      "Strong PvP toolkit with pressure and control",
      "Flexible class identity with healing offspec options"
    ],
    tradeoffs: [
      "Raw DPS rankings are usually below top pure DPS specs",
      "Raid value depends on group composition planning"
    ],
    nextSteps: "Lean into support value and group synergy rather than pure meter chasing."
  },
  {
    id: "priest_holy_disc",
    name: "Priest (Holy/Discipline Healer)",
    tags: ["healer", "utility", "pvp"],
    profile: {
      raid_dps: 0,
      easy_invites: 8,
      pvp_push: 9,
      flexibility: 8,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 8,
      low: 5,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 8,
      arena_high: 9,
      slot_low: 7,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 4,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 2,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 2,
      shadow_support: 8,
      meta: 8,
      balance: 9,
      fun: 8
    },
    strengths: [
      "High-value healer toolkit for raids and arena",
      "Strong cross-content flexibility",
      "Good pick if you enjoy reactive gameplay and decision density"
    ],
    tradeoffs: [
      "Less solo comfort than DPS choices",
      "High awareness expectations in difficult encounters"
    ],
    nextSteps: "Build strong healing fundamentals first, then branch into PvP-specific survival and control patterns."
  }
];

// Answer to profile key mappings
const answerMap = {
  goal: {
    raid_dps: "raid_dps",
    easy_invites: "easy_invites",
    pvp_push: "pvp_push",
    flexibility: "flexibility"
  },
  role: {
    ranged: "ranged",
    melee: "melee",
    tank: "tank",
    healer: "healer",
    hybrid: "hybrid"
  },
  complexity: {
    low: "low",
    mid: "mid",
    high: "high"
  },
  arena: {
    low: "arena_low",
    mid: "arena_mid",
    high: "arena_high"
  },
  slotPressure: {
    low: "slot_low",
    mid: "slot_mid",
    high: "slot_high"
  },
  gear: {
    low: "gear_low",
    mid: "gear_mid",
    high: "gear_high"
  },
  solo: {
    low: "solo_low",
    mid: "solo_mid",
    high: "solo_high"
  },
  demand: {
    low: "demand_low",
    mid: "demand_mid",
    high: "demand_high"
  },
  fantasy: {
    pet_master: "pet_master",
    dark_caster: "dark_caster",
    holy_warrior: "holy_warrior",
    totem_fighter: "totem_fighter",
    shapeshifter: "shapeshifter",
    weapon_master: "weapon_master",
    arcane_control: "arcane_control",
    shadow_support: "shadow_support"
  },
  mindset: {
    meta: "meta",
    balance: "balance",
    fun: "fun"
  }
};

// Scoring weights for each question category
const weights = {
  goal: 1.35,
  role: 1.35,
  complexity: 0.95,
  arena: 1.15,
  slotPressure: 0.85,
  gear: 0.9,
  solo: 0.9,
  demand: 1.1,
  fantasy: 1.1,
  mindset: 1.0
};

// Farming efficiency bonuses per class
const farmingBonuses = {
  bm_hunter: { open: 1, aoe: 1, gather: 2, instance: 2 },
  fire_mage: { open: 0, aoe: 2, gather: 1, instance: 0 },
  destro_warlock: { open: 1, aoe: 0, gather: 1, instance: 1 },
  feral_druid: { open: 1, aoe: 1, gather: 2, instance: 1 },
  prot_paladin: { open: 0, aoe: 3, gather: 0, instance: 3 },
  enhance_shaman: { open: 1, aoe: 0, gather: 1, instance: 0 },
  arms_fury_warrior: { open: -1, aoe: 0, gather: 0, instance: -1 },
  holy_paladin: { open: -2, aoe: -2, gather: -1, instance: -2 },
  resto_shaman: { open: -2, aoe: -2, gather: -1, instance: -2 },
  priest_holy_disc: { open: -2, aoe: -2, gather: -1, instance: -2 }
};
