// Class profiles and game data
const classProfiles = [
  {
    id: "bm_hunter",
    name: "Hunter (Beast Mastery)",
    tags: ["ranged", "pve_dps", "solo", "demand", "high_apm"],
    profile: {
      raid_dps: 10,
      easy_invites: 9,
      pvp_push: 7,
      flexibility: 4,
      ranged: 10,
      melee: 1,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 3,
      mid: 7,
      high: 9,
      arena_low: 3,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 8,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 5,
      solo_mid: 8,
      solo_high: 10,
      demand_low: 6,
      demand_mid: 9,
      demand_high: 10,
      pet_master: 10,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 2,
      arcane_control: 2,
      shadow_support: 0,
      meta: 9,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Top-tier sustained raid DPS through all major TBC phases",
      "High solo efficiency and safe farming with pet toolkit",
      "Consistent invite value in 25-man physical groups"
    ],
    tradeoffs: [
      "Ceiling gameplay includes timing-sensitive shot weaving",
      "Can feel repetitive if you dislike pet management"
    ],
    nextSteps: "Start as BM with 4pc Beast Lord path from dungeons, then optimize shot rhythm and pet uptime.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/hunter/beast-mastery/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/beast-mastery-hunter-pve-dps-guide"
    },
    farmingBonus: { open: 1, aoe: 1, gather: 2, instance: 2 }
  },
  {
    id: "surv_hunter",
    name: "Hunter (Survival)",
    tags: ["ranged", "pvp", "utility"],
    profile: {
      raid_dps: 7,
      easy_invites: 7,
      pvp_push: 9,
      flexibility: 6,
      ranged: 10,
      melee: 2,
      tank: 0,
      healer: 0,
      hybrid: 5,
      low: 4,
      mid: 7,
      high: 7,
      arena_low: 5,
      arena_mid: 8,
      arena_high: 8,
      slot_low: 5,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 7,
      gear_mid: 7,
      gear_high: 6,
      solo_low: 4,
      solo_mid: 6,
      solo_high: 7,
      demand_low: 4,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 6,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 3,
      arcane_control: 3,
      shadow_support: 0,
      meta: 6,
      balance: 8,
      fun: 9
    },
    strengths: [
      "Expose Weakness provides massive raid AP value in physical-heavy compositions",
      "Top-tier arena and BG toolkit with Wyvern Sting and superior kiting",
      "Agility stacking makes gearing intuitive and synergistic"
    ],
    tradeoffs: [
      "Personal DPS is noticeably lower than Beast Mastery",
      "Raid slot demand depends entirely on melee group composition"
    ],
    nextSteps: "Stack agility to maximise Expose Weakness value, then coordinate with melee group leads to confirm your utility slot.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/hunter/survival/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/survival-hunter-pve-dps-guide"
    },
    farmingBonus: { open: 0, aoe: 0, gather: 1, instance: 1 }
  },
  {
    id: "destro_warlock",
    name: "Warlock (Destruction)",
    tags: ["ranged", "pve_dps", "demand"],
    profile: {
      raid_dps: 10,
      easy_invites: 9,
      pvp_push: 6,
      flexibility: 5,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 6,
      mid: 8,
      high: 6,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 6,
      slot_low: 8,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 4,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 9,
      pet_master: 1,
      dark_caster: 10,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 3,
      shadow_support: 4,
      meta: 9,
      balance: 8,
      fun: 6
    },
    strengths: [
      "Reliable raid throughput and strong scaling",
      "Excellent raid utility (summons, stones, curses)",
      "Very stable spot in caster-centric comps"
    ],
    tradeoffs: [
      "Core rotation can feel simple over long sessions",
      "PvP options exist but are comp and spec dependent"
    ],
    nextSteps: "Gear through spell hit/spell power benchmarks, then refine curse and pet utility discipline.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warlock/destruction/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/destruction-warlock-pve-dps-guide"
    },
    farmingBonus: { open: 1, aoe: 0, gather: 1, instance: 1 }
  },
  {
    id: "fire_mage",
    name: "Mage (Fire)",
    tags: ["ranged", "pve_dps", "control"],
    profile: {
      raid_dps: 9,
      easy_invites: 7,
      pvp_push: 7,
      flexibility: 4,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 5,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 5,
      slot_mid: 7,
      slot_high: 8,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 8,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 4,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 4,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 10,
      shadow_support: 0,
      meta: 8,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Strong ranged DPS with high burst windows",
      "Great utility for dungeons and PvP control",
      "Good pick if you enjoy active casting cadence"
    ],
    tradeoffs: [
      "Raid slots can be tighter than lock/hunter in many comps",
      "Performance heavily depends on group buffs and kill times"
    ],
    nextSteps: "Prioritize hit cap and spell power upgrades, then optimize combust windows and utility usage.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/mage/fire/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/fire-mage-pve-dps-guide"
    },
    farmingBonus: { open: 0, aoe: 2, gather: 1, instance: 0 }
  },
  {
    id: "enhance_shaman",
    name: "Shaman (Enhancement)",
    tags: ["melee", "hybrid", "demand", "utility"],
    profile: {
      raid_dps: 7,
      easy_invites: 10,
      pvp_push: 7,
      flexibility: 9,
      ranged: 1,
      melee: 9,
      tank: 0,
      healer: 3,
      hybrid: 10,
      low: 4,
      mid: 8,
      high: 8,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 9,
      slot_mid: 10,
      slot_high: 9,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 7,
      solo_low: 5,
      solo_mid: 8,
      solo_high: 8,
      demand_low: 8,
      demand_mid: 10,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 1,
      totem_fighter: 10,
      shapeshifter: 0,
      weapon_master: 6,
      arcane_control: 0,
      shadow_support: 2,
      meta: 9,
      balance: 10,
      fun: 9
    },
    strengths: [
      "Extremely high raid demand in TBC due to group totem value",
      "Strong hybrid flexibility across PvE and PvP",
      "Engaging support-plus-damage gameplay"
    ],
    tradeoffs: [
      "Totem management can feel busy",
      "Dual-weapon gearing can be awkward in some loot environments"
    ],
    nextSteps: "Secure hit and weapon speed consistency early, then master totem timing per encounter.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/shaman/enhancement/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/enhancement-shaman-pve-dps-guide"
    },
    farmingBonus: { open: 1, aoe: 0, gather: 1, instance: 0 }
  },
  {
    id: "resto_shaman",
    name: "Shaman (Restoration)",
    tags: ["healer", "demand", "utility"],
    profile: {
      raid_dps: 0,
      easy_invites: 10,
      pvp_push: 8,
      flexibility: 9,
      ranged: 2,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 9,
      low: 6,
      mid: 8,
      high: 5,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 10,
      slot_mid: 10,
      slot_high: 9,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 4,
      demand_low: 9,
      demand_mid: 10,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 9,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 0,
      shadow_support: 3,
      meta: 10,
      balance: 9,
      fun: 8
    },
    strengths: [
      "One of the safest invite options in TBC raids",
      "Chain heal plus totems provide huge raid utility",
      "Competitive healer in arena formats"
    ],
    tradeoffs: [
      "Solo speed is weaker than DPS-focused specs",
      "High utility responsibility in optimized groups"
    ],
    nextSteps: "Build healing throughput basics first, then layer in totem swaps and utility discipline.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/shaman/restoration/pve-healing",
      icyveins: "https://www.icy-veins.com/tbc-classic/restoration-shaman-pve-healing-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  },
  {
    id: "feral_druid",
    name: "Druid (Feral Bear/Cat Hybrid)",
    tags: ["melee", "tank", "hybrid", "solo"],
    profile: {
      raid_dps: 6,
      easy_invites: 7,
      pvp_push: 7,
      flexibility: 10,
      ranged: 0,
      melee: 8,
      tank: 8,
      healer: 2,
      hybrid: 10,
      low: 4,
      mid: 8,
      high: 8,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 4,
      solo_mid: 9,
      solo_high: 10,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 10,
      weapon_master: 6,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 10,
      fun: 10
    },
    strengths: [
      "Top-tier flexibility between tanking and DPS assignments",
      "Excellent open-world sustain and movement",
      "Strong value in raids that need adaptable offtanking"
    ],
    tradeoffs: [
      "Pure cat DPS slots are less common than hybrid feral roles",
      "Performance quality depends on encounter role swapping"
    ],
    nextSteps: "Prepare both bear and cat sets early, and communicate your role flexibility with raid leads.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/druid/feral/pve-tank",
      icyveins: "https://www.icy-veins.com/tbc-classic/feral-druid-pve-tank-guide"
    },
    farmingBonus: { open: 1, aoe: 1, gather: 2, instance: 1 }
  },
  {
    id: "prot_paladin",
    name: "Paladin (Protection)",
    tags: ["tank", "utility", "demand"],
    profile: {
      raid_dps: 1,
      easy_invites: 8,
      pvp_push: 4,
      flexibility: 8,
      ranged: 0,
      melee: 1,
      tank: 10,
      healer: 1,
      hybrid: 8,
      low: 7,
      mid: 8,
      high: 4,
      arena_low: 3,
      arena_mid: 4,
      arena_high: 5,
      slot_low: 6,
      slot_mid: 8,
      slot_high: 7,
      gear_low: 5,
      gear_mid: 6,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 9,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 10,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 3,
      arcane_control: 0,
      shadow_support: 0,
      meta: 8,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Premier AoE tanking utility in TBC dungeons and raids",
      "Strong support identity with blessings and utility",
      "Can offer stable raid value when threat/gearing is managed"
    ],
    tradeoffs: [
      "Single-target tank optimization can be gear and setup sensitive",
      "Full-time raid tank slots are naturally limited"
    ],
    nextSteps: "Build separate threat and mitigation sets, then align group composition for reliable threat support.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/paladin/protection/pve-tank",
      icyveins: "https://www.icy-veins.com/tbc-classic/protection-paladin-pve-tank-guide"
    },
    farmingBonus: { open: 0, aoe: 3, gather: 0, instance: 3 }
  },
  {
    id: "holy_paladin",
    name: "Paladin (Holy)",
    tags: ["healer", "utility", "demand"],
    profile: {
      raid_dps: 0,
      easy_invites: 8,
      pvp_push: 7,
      flexibility: 6,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 6,
      low: 8,
      mid: 8,
      high: 4,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 7,
      slot_low: 7,
      slot_mid: 8,
      slot_high: 7,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 2,
      solo_mid: 4,
      solo_high: 3,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 10,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Reliable single-target healing and excellent mana longevity",
      "Desired utility package in raid environments",
      "Works well for players who like stability and clean execution"
    ],
    tradeoffs: [
      "Lower solo speed than DPS classes",
      "Playstyle can feel repetitive if you prefer high APM"
    ],
    nextSteps: "Prioritize throughput and mana stats early, then refine cooldown and utility timing in raids.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/paladin/holy/pve-healing",
      icyveins: "https://www.icy-veins.com/tbc-classic/holy-paladin-pve-healing-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  },
  {
    id: "arms_warrior",
    name: "Warrior (Arms)",
    tags: ["melee", "high_apm", "pvp"],
    profile: {
      raid_dps: 6,
      easy_invites: 5,
      pvp_push: 10,
      flexibility: 6,
      ranged: 0,
      melee: 10,
      tank: 1,
      healer: 0,
      hybrid: 3,
      low: 3,
      mid: 6,
      high: 8,
      arena_low: 6,
      arena_mid: 9,
      arena_high: 10,
      slot_low: 4,
      slot_mid: 6,
      slot_high: 6,
      gear_low: 4,
      gear_mid: 6,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 6,
      solo_high: 6,
      demand_low: 4,
      demand_mid: 6,
      demand_high: 6,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 10,
      arcane_control: 0,
      shadow_support: 0,
      meta: 7,
      balance: 7,
      fun: 9
    },
    strengths: [
      "Top-tier PvP pressure and mortal strike utility",
      "Strong weapon-focused identity with impactful cooldowns",
      "Can bring raid debuff utility while staying melee-focused"
    ],
    tradeoffs: [
      "Raid personal DPS is usually below dedicated PvE melee builds",
      "Performance is very gear and support dependent"
    ],
    nextSteps: "Build around PvP pressure first, then tune raid utility and hit thresholds if you flex into PvE.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warrior/arms/pvp-overview",
      icyveins: "https://www.icy-veins.com/tbc-classic/arms-warrior-pvp-guide"
    },
    farmingBonus: { open: -1, aoe: 0, gather: 0, instance: -1 }
  },
  {
    id: "fury_warrior",
    name: "Warrior (Fury)",
    tags: ["melee", "high_apm", "scaling", "pve_dps"],
    profile: {
      raid_dps: 9,
      easy_invites: 4,
      pvp_push: 5,
      flexibility: 4,
      ranged: 0,
      melee: 10,
      tank: 1,
      healer: 0,
      hybrid: 2,
      low: 2,
      mid: 5,
      high: 10,
      arena_low: 2,
      arena_mid: 4,
      arena_high: 5,
      slot_low: 3,
      slot_mid: 5,
      slot_high: 8,
      gear_low: 3,
      gear_mid: 6,
      gear_high: 10,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 5,
      demand_low: 2,
      demand_mid: 4,
      demand_high: 6,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 9,
      arcane_control: 0,
      shadow_support: 0,
      meta: 8,
      balance: 6,
      fun: 8
    },
    strengths: [
      "Very high PvE ceiling with strong scaling in raid gear",
      "Excellent fit for players who enjoy fast melee throughput",
      "Strong synergy with physical raid support"
    ],
    tradeoffs: [
      "Weak early progression if gear and buffs are lacking",
      "PvP value is much lower than Arms in most comps"
    ],
    nextSteps: "Prioritize PvE hit and expertise breakpoints, then scale into high-end raid weapons and support buffs.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warrior/fury/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/fury-warrior-pve-dps-guide"
    },
    farmingBonus: { open: -1, aoe: 0, gather: 0, instance: -1 }
  },
  {
    id: "priest_shadow",
    name: "Priest (Shadow)",
    tags: ["ranged", "utility", "support_dps"],
    profile: {
      raid_dps: 5,
      easy_invites: 7,
      pvp_push: 8,
      flexibility: 7,
      ranged: 9,
      melee: 0,
      tank: 0,
      healer: 2,
      hybrid: 7,
      low: 5,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 7,
      gear_mid: 7,
      gear_high: 6,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 7,
      demand_low: 5,
      demand_mid: 8,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 7,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 4,
      shadow_support: 10,
      meta: 8,
      balance: 9,
      fun: 8
    },
    strengths: [
      "Great utility-DPS niche in caster groups",
      "Strong PvP toolkit with pressure and control",
      "Flexible class identity with healing offspec options"
    ],
    tradeoffs: [
      "Raw DPS rankings are usually below top pure DPS specs",
      "Raid value depends on group composition planning"
    ],
    nextSteps: "Lean into support value and group synergy rather than pure meter chasing.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/priest/shadow/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/shadow-priest-pve-dps-guide"
    },
    farmingBonus: { open: 0, aoe: 0, gather: 0, instance: 0 }
  },
  {
    id: "priest_holy",
    name: "Priest (Holy)",
    tags: ["healer", "utility", "demand"],
    profile: {
      raid_dps: 0,
      easy_invites: 9,
      pvp_push: 5,
      flexibility: 7,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 7,
      low: 6,
      mid: 8,
      high: 6,
      arena_low: 3,
      arena_mid: 5,
      arena_high: 6,
      slot_low: 8,
      slot_mid: 9,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 4,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 9,
      pet_master: 0,
      dark_caster: 1,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 1,
      shadow_support: 9,
      meta: 8,
      balance: 9,
      fun: 7
    },
    strengths: [
      "One of the most reliable raid healers in TBC",
      "Strong throughput with Circle of Healing and raid cooldowns",
      "High demand in progression content and structured guilds"
    ],
    tradeoffs: [
      "Weak solo capability and slow open-world play",
      "Less flexible in PvP formats compared to Discipline"
    ],
    nextSteps: "Focus on spell power and MP5 early, then refine cooldown timing and group assignment discipline.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/priest/holy/pve-healing",
      icyveins: "https://www.icy-veins.com/tbc-classic/holy-priest-pve-healing-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  },
  {
    id: "priest_discipline",
    name: "Priest (Discipline)",
    tags: ["healer", "pvp", "utility"],
    profile: {
      raid_dps: 0,
      easy_invites: 7,
      pvp_push: 10,
      flexibility: 8,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 9,
      hybrid: 8,
      low: 5,
      mid: 7,
      high: 7,
      arena_low: 5,
      arena_mid: 9,
      arena_high: 10,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 6,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 4,
      demand_low: 5,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 3,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 3,
      shadow_support: 9,
      meta: 8,
      balance: 9,
      fun: 9
    },
    strengths: [
      "Top-tier arena healer with unmatched control and survival tools",
      "Power Word: Shield and Fear Ward make you invaluable in PvP",
      "High skill ceiling with rewarding decision-making in arena"
    ],
    tradeoffs: [
      "Raid healing output is lower than Holy in PvE content",
      "Requires strong arena partners to fully shine"
    ],
    nextSteps: "Build resilience and spell power for arena, then master Fear Ward timing and shield rotation.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/priest/discipline/pvp",
      icyveins: "https://www.icy-veins.com/tbc-classic/discipline-priest-pvp-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  },
  {
    id: "marks_hunter",
    name: "Hunter (Marksmanship)",
    tags: ["ranged", "pvp", "utility"],
    profile: {
      raid_dps: 8,
      easy_invites: 7,
      pvp_push: 9,
      flexibility: 5,
      ranged: 10,
      melee: 1,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 4,
      mid: 7,
      high: 8,
      arena_low: 6,
      arena_mid: 8,
      arena_high: 9,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 5,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 3,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 8,
      arcane_control: 5,
      shadow_support: 0,
      meta: 8,
      balance: 8,
      fun: 8
    },
    strengths: [
      "Strong PvP damage and precision with coordinated cooldown windows",
      "Excellent arena performer with enhanced control and burst",
      "Good raid DPS with strong single-target focus"
    ],
    tradeoffs: [
      "Lower steady raid DPS compared to Beast Mastery",
      "Less forgiving if you miss cooldown windows"
    ],
    nextSteps: "Master precision shot timing and cooldown alignment, then optimize with group buffs.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/hunter/marksmanship/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/marksmanship-hunter-pve-dps-guide"
    },
    farmingBonus: { open: 0, aoe: 0, gather: 1, instance: 1 }
  },
  {
    id: "prot_warrior",
    name: "Warrior (Protection)",
    tags: ["tank", "utility", "demand"],
    profile: {
      raid_dps: 1,
      easy_invites: 8,
      pvp_push: 3,
      flexibility: 6,
      ranged: 0,
      melee: 1,
      tank: 10,
      healer: 0,
      hybrid: 3,
      low: 5,
      mid: 7,
      high: 6,
      arena_low: 2,
      arena_mid: 3,
      arena_high: 4,
      slot_low: 5,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 8,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 6,
      demand_low: 5,
      demand_mid: 8,
      demand_high: 9,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 5,
      arcane_control: 0,
      shadow_support: 0,
      meta: 9,
      balance: 7,
      fun: 6
    },
    strengths: [
      "Game-changing cooldowns like Last Stand and Shield Wall",
      "Superior damage mitigation and crush-immunity",
      "Designed specifically for many TBC encounters"
    ],
    tradeoffs: [
      "Single-target threat can be tight with high-DPS groups",
      "Less scaling with gear compared to other tank specs"
    ],
    nextSteps: "Build separate threat and mitigation gear sets, then coordinate closely with raid leadership.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warrior/protection/pve-tank",
      icyveins: "https://www.icy-veins.com/tbc-classic/protection-warrior-tank-pve-guide"
    },
    farmingBonus: { open: -1, aoe: 2, gather: 0, instance: 2 }
  },
  {
    id: "ret_paladin",
    name: "Paladin (Retribution)",
    tags: ["melee", "dps", "utility", "demand"],
    profile: {
      raid_dps: 7,
      easy_invites: 9,
      pvp_push: 8,
      flexibility: 6,
      ranged: 0,
      melee: 10,
      tank: 1,
      healer: 1,
      hybrid: 5,
      low: 5,
      mid: 7,
      high: 8,
      arena_low: 5,
      arena_mid: 8,
      arena_high: 9,
      slot_low: 8,
      slot_mid: 9,
      slot_high: 8,
      gear_low: 5,
      gear_mid: 6,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 6,
      solo_high: 7,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 10,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 7,
      arcane_control: 0,
      shadow_support: 2,
      meta: 9,
      balance: 8,
      fun: 8
    },
    strengths: [
      "Highest melee DPS in raid comps with improved seals and abilities",
      "Unique utility buffs make you highly sought after",
      "Strong PvP burst potential with Avenging Wrath"
    ],
    tradeoffs: [
      "Mana management can be tight in longer encounters",
      "Performance heavily gear-dependent early on"
    ],
    nextSteps: "Prioritize Expertise early, then build Strength and attack power scaling.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/paladin/retribution/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/retribution-paladin-dps-pve-guide"
    },
    farmingBonus: { open: 0, aoe: 1, gather: 1, instance: 1 }
  },
  {
    id: "assass_rogue",
    name: "Rogue (Assassination)",
    tags: ["melee", "dps", "poison"],
    profile: {
      raid_dps: 6,
      easy_invites: 5,
      pvp_push: 7,
      flexibility: 4,
      ranged: 0,
      melee: 10,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 3,
      mid: 6,
      high: 7,
      arena_low: 5,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 4,
      slot_mid: 5,
      slot_high: 6,
      gear_low: 4,
      gear_mid: 6,
      gear_high: 8,
      solo_low: 4,
      solo_mid: 6,
      solo_high: 7,
      demand_low: 3,
      demand_mid: 5,
      demand_high: 6,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 6,
      arcane_control: 0,
      shadow_support: 3,
      meta: 6,
      balance: 7,
      fun: 7
    },
    strengths: [
      "Strong poison-based damage and DoT application",
      "Decent PvP control with silences and stuns",
      "Good utility in smaller group content"
    ],
    tradeoffs: [
      "Lower DPS than Combat Rogues in raids",
      "Less demand in organized raid compositions"
    ],
    nextSteps: "Master poison management and timing, focus on high-uptime content.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/rogue/assassination/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/assassination-rogue-dps-pve-guide"
    },
    farmingBonus: { open: -1, aoe: -1, gather: 0, instance: 0 }
  },
  {
    id: "combat_rogue",
    name: "Rogue (Combat)",
    tags: ["melee", "dps", "high_apm"],
    profile: {
      raid_dps: 8,
      easy_invites: 6,
      pvp_push: 6,
      flexibility: 4,
      ranged: 0,
      melee: 10,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 2,
      mid: 6,
      high: 9,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 7,
      slot_low: 5,
      slot_mid: 7,
      slot_high: 8,
      gear_low: 3,
      gear_mid: 6,
      gear_high: 10,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 6,
      demand_low: 4,
      demand_mid: 6,
      demand_high: 7,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 10,
      arcane_control: 0,
      shadow_support: 2,
      meta: 8,
      balance: 7,
      fun: 8
    },
    strengths: [
      "Top physical DPS in raids with proper gearing",
      "Highly rewarding weapon-scaling mechanics",
      "Best Rogue option for serious raiding"
    ],
    tradeoffs: [
      "Requires excellent gear to shine early",
      "Shares loot with Warriors and Hunters heavily"
    ],
    nextSteps: "Secure solid weapons early, then stack Strength and Crit as you gear.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/rogue/combat/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/combat-rogue-dps-pve-guide"
    },
    farmingBonus: { open: -1, aoe: -1, gather: 0, instance: 0 }
  },
  {
    id: "subtlety_rogue",
    name: "Rogue (Subtlety)",
    tags: ["melee", "pvp", "utility"],
    profile: {
      raid_dps: 5,
      easy_invites: 4,
      pvp_push: 10,
      flexibility: 5,
      ranged: 0,
      melee: 10,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 3,
      mid: 5,
      high: 6,
      arena_low: 7,
      arena_mid: 9,
      arena_high: 10,
      slot_low: 3,
      slot_mid: 4,
      slot_high: 5,
      gear_low: 4,
      gear_mid: 5,
      gear_high: 7,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 6,
      demand_low: 2,
      demand_mid: 4,
      demand_high: 5,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 7,
      arcane_control: 1,
      shadow_support: 5,
      meta: 7,
      balance: 6,
      fun: 9
    },
    strengths: [
      "Unmatched PvP toolkit with Shadowstep and superior kiting",
      "Excellent arena viability with control abilities",
      "Playstyle rewards skill and positioning"
    ],
    tradeoffs: [
      "Poor raid DPS compared to Combat",
      "Very limited PvE utility and raid demand"
    ],
    nextSteps: "Focus on PvP content and arenas instead of raiding.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/rogue/subtlety/pvp",
      icyveins: "https://www.icy-veins.com/tbc-classic/subtlety-rogue-pvp-guide"
    },
    farmingBonus: { open: -1, aoe: -1, gather: 0, instance: -1 }
  },
  {
    id: "arcane_mage",
    name: "Mage (Arcane)",
    tags: ["ranged", "pve_dps", "control"],
    profile: {
      raid_dps: 10,
      easy_invites: 8,
      pvp_push: 6,
      flexibility: 5,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 6,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 7,
      slot_low: 7,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 6,
      gear_mid: 8,
      gear_high: 9,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 5,
      demand_mid: 8,
      demand_high: 9,
      pet_master: 0,
      dark_caster: 6,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 10,
      shadow_support: 0,
      meta: 10,
      balance: 7,
      fun: 8
    },
    strengths: [
      "S-Tier DPS with highest ceiling of all three specs",
      "Best burst damage and mana conversion",
      "Extremely easy to gear in early phases"
    ],
    tradeoffs: [
      "Heavily reliant on Shadow Priest mana support",
      "Gets weaker the longer fights go on",
      "Most challenging of all Mage specs to play optimally"
    ],
    nextSteps: "Prioritize Intellect and Spirit early, then focus on spell power and mastering mana management.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/mage/arcane/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/arcane-mage-dps-pve-guide"
    },
    farmingBonus: { open: 0, aoe: 1, gather: 1, instance: 0 }
  },
  {
    id: "frost_mage",
    name: "Mage (Frost)",
    tags: ["ranged", "pve_dps", "control"],
    profile: {
      raid_dps: 7,
      easy_invites: 6,
      pvp_push: 9,
      flexibility: 5,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 1,
      low: 5,
      mid: 7,
      high: 7,
      arena_low: 5,
      arena_mid: 8,
      arena_high: 9,
      slot_low: 5,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 8,
      solo_low: 6,
      solo_mid: 8,
      solo_high: 9,
      demand_low: 4,
      demand_mid: 6,
      demand_high: 7,
      pet_master: 0,
      dark_caster: 3,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 9,
      shadow_support: 0,
      meta: 7,
      balance: 8,
      fun: 8
    },
    strengths: [
      "Best PvP Mage spec with superior control and CC",
      "Great soloing and farming with AoE slow",
      "High survivability with defensive tools"
    ],
    tradeoffs: [
      "Lower PvE DPS than Arcane and Fire",
      "Requires more support to match other specs in raids"
    ],
    nextSteps: "Build for survivability first, then layer in spell power scaling.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/mage/frost/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/frost-mage-dps-pve-guide"
    },
    farmingBonus: { open: 1, aoe: 3, gather: 1, instance: 1 }
  },
  {
    id: "affliction_warlock",
    name: "Warlock (Affliction)",
    tags: ["ranged", "pve_dps", "support"],
    profile: {
      raid_dps: 7,
      easy_invites: 8,
      pvp_push: 7,
      flexibility: 6,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 2,
      low: 6,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 7,
      slot_mid: 8,
      slot_high: 8,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 8,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 6,
      demand_mid: 8,
      demand_high: 9,
      pet_master: 1,
      dark_caster: 10,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 2,
      shadow_support: 6,
      meta: 8,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Excellent multi-target DPS and DoT application",
      "Unique curse utility highly valued in raids",
      "Strong self-sustain with drain abilities"
    ],
    tradeoffs: [
      "Lower single-target DPS than Destruction",
      "Raid slot demand depends on group composition"
    ],
    nextSteps: "Build spell power early, then focus on Haste to increase DoT application speed.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warlock/affliction/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/affliction-warlock-dps-pve-guide"
    },
    farmingBonus: { open: 1, aoe: 2, gather: 1, instance: 1 }
  },
  {
    id: "demo_warlock",
    name: "Warlock (Demonology)",
    tags: ["ranged", "pve_dps", "support"],
    profile: {
      raid_dps: 7,
      easy_invites: 7,
      pvp_push: 5,
      flexibility: 7,
      ranged: 10,
      melee: 0,
      tank: 0,
      healer: 0,
      hybrid: 5,
      low: 5,
      mid: 7,
      high: 6,
      arena_low: 3,
      arena_mid: 5,
      arena_high: 6,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 7,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 5,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 8,
      dark_caster: 8,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 1,
      shadow_support: 5,
      meta: 7,
      balance: 7,
      fun: 8
    },
    strengths: [
      "Enhanced demon abilities provide solid DPS and utility",
      "Good flexibility with demon choice for different encounters",
      "Strong soloing potential with pet tanks"
    ],
    tradeoffs: [
      "DPS is not competitive with other specs in organized raids",
      "Very limited passive group benefit"
    ],
    nextSteps: "Master demon management and choose pets based on encounter mechanics.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/warlock/demonology/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/demonology-warlock-dps-pve-guide"
    },
    farmingBonus: { open: 1, aoe: 1, gather: 2, instance: 2 }
  },
  {
    id: "elemental_shaman",
    name: "Shaman (Elemental)",
    tags: ["ranged", "pve_dps", "support"],
    profile: {
      raid_dps: 6,
      easy_invites: 9,
      pvp_push: 7,
      flexibility: 7,
      ranged: 10,
      melee: 1,
      tank: 0,
      healer: 2,
      hybrid: 6,
      low: 6,
      mid: 8,
      high: 7,
      arena_low: 4,
      arena_mid: 7,
      arena_high: 8,
      slot_low: 8,
      slot_mid: 9,
      slot_high: 8,
      gear_low: 6,
      gear_mid: 7,
      gear_high: 6,
      solo_low: 4,
      solo_mid: 6,
      solo_high: 7,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 2,
      holy_warrior: 1,
      totem_fighter: 10,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 5,
      shadow_support: 1,
      meta: 9,
      balance: 9,
      fun: 9
    },
    strengths: [
      "Best support caster with Totem of Wrath and Bloodlust",
      "Excellent DPS at low gear levels",
      "High raid demand makes invites very reliable"
    ],
    tradeoffs: [
      "Scales poorly with gear compared to pure DPS",
      "Mana management issues in longer fights"
    ],
    nextSteps: "Build for spell hit and crit priority, then layer in Haste and spell power.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/shaman/elemental/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/elemental-shaman-dps-pve-guide"
    },
    farmingBonus: { open: 0, aoe: 1, gather: 1, instance: 1 }
  },
  {
    id: "balance_druid",
    name: "Druid (Balance)",
    tags: ["ranged", "pve_dps", "hybrid"],
    profile: {
      raid_dps: 6,
      easy_invites: 7,
      pvp_push: 6,
      flexibility: 9,
      ranged: 9,
      melee: 2,
      tank: 1,
      healer: 2,
      hybrid: 10,
      low: 5,
      mid: 7,
      high: 7,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 7,
      slot_low: 6,
      slot_mid: 7,
      slot_high: 7,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 5,
      solo_mid: 7,
      solo_high: 8,
      demand_low: 5,
      demand_mid: 7,
      demand_high: 8,
      pet_master: 0,
      dark_caster: 5,
      holy_warrior: 0,
      totem_fighter: 0,
      shapeshifter: 10,
      weapon_master: 0,
      arcane_control: 6,
      shadow_support: 3,
      meta: 7,
      balance: 9,
      fun: 8
    },
    strengths: [
      "Maximum flexibility to handle raid role changes",
      "Excellent open-world versatility",
      "Strong hybrid identity with Moonkin utility"
    ],
    tradeoffs: [
      "Pure DPS rankings lower than dedicated ranged specs",
      "Performance depends on encounter adaptability requirements"
    ],
    nextSteps: "Build intellect and spell power, prepare offspec gear for emergencies.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/druid/balance/pve-dps",
      icyveins: "https://www.icy-veins.com/tbc-classic/balance-druid-dps-pve-guide"
    },
    farmingBonus: { open: 1, aoe: 1, gather: 2, instance: 1 }
  },
  {
    id: "resto_druid",
    name: "Druid (Restoration)",
    tags: ["healer", "hybrid", "utility"],
    profile: {
      raid_dps: 0,
      easy_invites: 9,
      pvp_push: 6,
      flexibility: 9,
      ranged: 2,
      melee: 0,
      tank: 1,
      healer: 10,
      hybrid: 9,
      low: 6,
      mid: 8,
      high: 6,
      arena_low: 4,
      arena_mid: 6,
      arena_high: 7,
      slot_low: 8,
      slot_mid: 9,
      slot_high: 9,
      gear_low: 7,
      gear_mid: 8,
      gear_high: 7,
      solo_low: 3,
      solo_mid: 5,
      solo_high: 5,
      demand_low: 7,
      demand_mid: 9,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 1,
      totem_fighter: 0,
      shapeshifter: 9,
      weapon_master: 0,
      arcane_control: 1,
      shadow_support: 2,
      meta: 9,
      balance: 9,
      fun: 8
    },
    strengths: [
      "High raid demand with excellent throughput and utility",
      "Best healing mobility with instant cast abilities",
      "Flex tank potential adds immense group value"
    ],
    tradeoffs: [
      "Solo play and farming speed is weak",
      "High responsibility in raid composition planning"
    ],
    nextSteps: "Build healing throughput stats first, then prepare flexible gear for tanking emergencies.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/druid/restoration/pve-healing",
      icyveins: "https://www.icy-veins.com/tbc-classic/restoration-druid-healer-pve-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  },
  {
    id: "holy_priest_buffer",
    name: "Priest (Holy - Divine Spirit Support)",
    tags: ["healer", "utility", "support", "demand"],
    profile: {
      raid_dps: 0,
      easy_invites: 10,
      pvp_push: 4,
      flexibility: 6,
      ranged: 1,
      melee: 0,
      tank: 0,
      healer: 10,
      hybrid: 5,
      low: 7,
      mid: 9,
      high: 5,
      arena_low: 2,
      arena_mid: 4,
      arena_high: 5,
      slot_low: 9,
      slot_mid: 10,
      slot_high: 8,
      gear_low: 8,
      gear_mid: 8,
      gear_high: 6,
      solo_low: 2,
      solo_mid: 3,
      solo_high: 2,
      demand_low: 8,
      demand_mid: 10,
      demand_high: 10,
      pet_master: 0,
      dark_caster: 0,
      holy_warrior: 1,
      totem_fighter: 0,
      shapeshifter: 0,
      weapon_master: 0,
      arcane_control: 0,
      shadow_support: 10,
      meta: 9,
      balance: 8,
      fun: 7
    },
    strengths: [
      "Highest possible raid value as primary buff bot for caster groups",
      "Divine Spirit and Focus make you invaluable to DPS",
      "Extremely stable raid role in any progression guild"
    ],
    tradeoffs: [
      "Pure healing output is lower than non-support focused Holy",
      "Very weak solo capability and open-world play",
      "Role is purely support-oriented with little personal glory"
    ],
    nextSteps: "Prioritize Spirit and healing stats, focus all efforts on group buff uptime and coordination.",
    guides: {
      wowhead: "https://www.wowhead.com/tbc-classic/guide/classes/priest/holy/pve-healing",
      icyveins: "https://www.icy-veins.com/tbc-classic/holy-priest-healer-pve-guide"
    },
    farmingBonus: { open: -2, aoe: -2, gather: -1, instance: -2 }
  }
];

// Answer to profile key mappings
const answerMap = {
  goal: {
    raid_dps: "raid_dps",
    easy_invites: "easy_invites",
    pvp_push: "pvp_push",
    flexibility: "flexibility"
  },
  role: {
    ranged: "ranged",
    melee: "melee",
    tank: "tank",
    healer: "healer",
    hybrid: "hybrid"
  },
  complexity: {
    low: "low",
    mid: "mid",
    high: "high"
  },
  arena: {
    low: "arena_low",
    mid: "arena_mid",
    high: "arena_high"
  },
  slotPressure: {
    low: "slot_low",
    mid: "slot_mid",
    high: "slot_high"
  },
  gear: {
    low: "gear_low",
    mid: "gear_mid",
    high: "gear_high"
  },
  solo: {
    low: "solo_low",
    mid: "solo_mid",
    high: "solo_high"
  },
  demand: {
    low: "demand_low",
    mid: "demand_mid",
    high: "demand_high"
  },
  gearUniqueness: {
    shared: "gear_shared",
    balanced: "gear_balanced",
    unique: "gear_unique"
  },
  fantasy: {
    pet_master: "pet_master",
    dark_caster: "dark_caster",
    holy_warrior: "holy_warrior",
    totem_fighter: "totem_fighter",
    shapeshifter: "shapeshifter",
    weapon_master: "weapon_master",
    arcane_control: "arcane_control",
    shadow_support: "shadow_support"
  },
  mindset: {
    meta: "meta",
    balance: "balance",
    fun: "fun"
  }
};

// Scoring weights for each question category
const weights = {
  goal: 1.35,
  role: 1.35,
  complexity: 0.95,
  arena: 1.15,
  slotPressure: 0.85,
  gear: 0.9,
  solo: 0.9,
  demand: 1.1,
  gearUniqueness: 0.95,
  fantasy: 1.1,
  mindset: 1.0
};


